### ISSUE TITLE
Docs: Feedback for About Taxi

### ISSUE THREAD

**Issue by JamesHazelcast** [hazelcast/hz-flow-docs#91]
Hi, I have some feedback about [this page](https://github.com/hazelcast/hz-flow-docs/edit/main/docs/modules/introduction/pages/about-taxi.adoc)

This sentence:
> Taxi is semantic type system which essentially allows you to state that "This Thing is the same as That Thing".

is missing an article before "semantic type system"

Nit, this sentence:
> Because Taxi describes data semantically using rich semantic types rather than field names [...]

might be more readable written as:
> Because Taxi describes data using rich semantic types rather than field names [...]

since if you're using rich semantic types, it implies the data is described semantically

Towards the end of the page, we have the section:
> Taxi can partially describe [...]

From a user perspective, my first thought was "why partially?" but this is not explained here - I think it would be nice to cover a bit more detail after this section

**Comment by amandalindsay** [comment]
Fixed and also added a note to explain that you'd use Taxi to enhance existing specs rather than replace them
